'use client'
import Nav from './components/Nav'
import './globals.css'
import {Rajdhani} from 'next/font/google'
import { useFirebase } from './store/useFirebase'
import { useEffect } from 'react'

const rajdhani=Rajdhani({weight:['400','700'],subsets:['latin'],
display:'swap'})

export const metadata = {
  title: 'ProductHunt',
  description: 'Generated by create next app',
  
}

export default function RootLayout({ children }) {
  const {auth,onAuth,setUser}=useFirebase()
  
  useEffect(()=>{

    onAuth(auth,(user)=>{
          if(user){
            setUser(user)
            console.log(user);
          }
          else{
            return setUser(null)
          }
          
    })


  },[])
  return (
    <html lang="en">
      <body class="bg-slate-950" >
       <Nav/>
        <main>
        {children}
        </main>
        <footer><h2>Footer</h2></footer>
        </body>
    </html>
  )
}
