import Nav from './components/Nav'
import './globals.css'
import {Rajdhani} from 'next/font/google'

const rajdhani=Rajdhani({weight:['400','700'],subsets:['latin'],
display:'swap'})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  
}

export default function RootLayout({ children }) {
  return (
    <html className={rajdhani.className} lang="en">
      <body className="">
       <Nav/>
        <main>
        {children}
        </main>
        <footer><h2>Footer</h2></footer>
        </body>
    </html>
  )
}
